### ISSUE TITLE
Pondus modded

### ISSUE THREAD

**Issue by jensz12** [arberg/docker-minecraft#1]
Psst, jeg har altså også en server udgave af Pondus Modded, som gør det nemt at sætte den op 

Du kan se den her https://www.curseforge.com/minecraft/modpacks/pondus/files/2548541

Ellers er det fedt at se du har inkluderet modpacken :-D

**Comment by arberg** [comment]
Jeg har linket til din nu, så har jeg den også hvis jeg skulle have lyst til at se på det i fremtiden.

kh Alex
